### ISSUE TITLE
JWSACruncher v2.2.3 doesn't run with Java 11

### ISSUE THREAD

**Issue by afrimberger** [jdemetra/jwsacruncher#99]
Executing JWSACruncher v2.2.3 with Java 11 leads to the following exception (due to JAXB removal in Java 11):
```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at ec.jwsacruncher.App.generateDefaultConfigFile(App.java:95)
	at ec.jwsacruncher.App.main(App.java:72)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 2 more
```

According to the pom.xml and the the Github Workflows, the code seems to be already prepared for Java 11.
Could you please create a new release?

**Comment by charphi** [comment]
Done in 248572482f8047d3b340c1c465962e0f6569e031
For the new release, I'm not sure if or when we can release one as we are working on the next version.
